{"kind":"symbol","schemaVersion":{"major":0,"patch":0,"minor":3},"primaryContentSections":[{"declarations":[{"tokens":[{"text":"init","kind":"keyword"},{"text":"(","kind":"text"},{"text":"_","kind":"externalParam"},{"kind":"text","text":" "},{"kind":"internalParam","text":"message"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"kind":"text","text":")"}],"languages":["swift"],"platforms":["macOS"]}],"kind":"declarations"}],"identifier":{"url":"doc:\/\/ArgumentParser\/documentation\/ArgumentParser\/ValidationError\/init(_:)","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Creates a new validation error with the given message."}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/argumentparser\/validationerror\/init(_:)"]}],"metadata":{"externalID":"s:14ArgumentParser15ValidationErrorVyACSScfc","title":"init(_:)","roleHeading":"Initializer","symbolKind":"init","role":"symbol","modules":[{"name":"ArgumentParser"}],"fragments":[{"text":"init","kind":"identifier"},{"text":"(","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":")","kind":"text"}]},"hierarchy":{"paths":[["doc:\/\/ArgumentParser\/documentation\/ArgumentParser","doc:\/\/ArgumentParser\/documentation\/ArgumentParser\/ValidationError"]]},"sections":[],"references":{"doc://ArgumentParser/documentation/ArgumentParser":{"title":"ArgumentParser","role":"collection","abstract":[{"type":"text","text":"Straightforward, type-safe argument parsing for Swift."}],"identifier":"doc:\/\/ArgumentParser\/documentation\/ArgumentParser","kind":"symbol","type":"topic","url":"\/documentation\/argumentparser"},"doc://ArgumentParser/documentation/ArgumentParser/ValidationError":{"title":"ValidationError","type":"topic","abstract":[{"text":"An error type that is presented to the user as an error with parsing their","type":"text"},{"type":"text","text":" "},{"text":"command-line input.","type":"text"}],"role":"symbol","fragments":[{"text":"struct","kind":"keyword"},{"text":" ","kind":"text"},{"text":"ValidationError","kind":"identifier"}],"navigatorTitle":[{"text":"ValidationError","kind":"identifier"}],"identifier":"doc:\/\/ArgumentParser\/documentation\/ArgumentParser\/ValidationError","kind":"symbol","url":"\/documentation\/argumentparser\/validationerror"},"doc://ArgumentParser/documentation/ArgumentParser/ValidationError/init(_:)":{"fragments":[{"text":"init","kind":"identifier"},{"text":"(","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":")","kind":"text"}],"identifier":"doc:\/\/ArgumentParser\/documentation\/ArgumentParser\/ValidationError\/init(_:)","title":"init(_:)","abstract":[{"text":"Creates a new validation error with the given message.","type":"text"}],"kind":"symbol","role":"symbol","url":"\/documentation\/argumentparser\/validationerror\/init(_:)","type":"topic"}}}